name = input('What is your name? ')
age = input('How old are you? ')
country = input('Where are you live? ')
print ('Hello, %s!' %name)
print('Your age is ' + age)
print('You live in ' + country)
